/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipresupuesto;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modulocore.Core;
import modulocore.Programa;
import modulopresuprogramas.Actividad;
import modulopresuprogramas.Plan;
import modulopresuprogramas.Proyecto;
import modulopresuprogramas.Responsable;

/**
 *
 * @author JAIRO
 */
public class VentanaPresupuesto extends javax.swing.JFrame {

    /**
     * core
     */
    private Core core;
    
    /**
     * planes agregados a el presupuesto
     */
    private List<Plan> planes;

    /**
     * Creates new form VentanaPresupuesto
     */
    public VentanaPresupuesto() {
        initComponents();
        core = new Core();
        planes = new ArrayList<>();
        jRBActividad.setSelected(true);
        autoIncremental();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFCedula = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jRBActividad = new javax.swing.JRadioButton();
        jRBProyecto = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFPresupuesto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCBCiudad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jLInfo = new javax.swing.JLabel();
        jTFInfoPlan = new javax.swing.JTextField();
        jBAgregarPlan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jBCrearPrograma = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTFCodigoPrograma = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTInfoPrograma = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jBEliminarPrograma = new javax.swing.JButton();
        jBMas = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTDetalles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Responsable"));

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombre");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTFCedula))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear plan"));

        buttonGroup1.add(jRBActividad);
        jRBActividad.setText("Actividad");
        jRBActividad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRBActividadStateChanged(evt);
            }
        });

        buttonGroup1.add(jRBProyecto);
        jRBProyecto.setText("Proyecto");
        jRBProyecto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRBProyectoStateChanged(evt);
            }
        });

        jLabel3.setText("Codigo");

        jLabel4.setText("Presupuesto");

        jLabel5.setText("Ciudad");

        jCBCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Armenia", "Bogota", "Cali", "Medellin", "Neiva" }));

        jLabel6.setText("Descripcion");

        jTADescripcion.setColumns(20);
        jTADescripcion.setRows(5);
        jScrollPane1.setViewportView(jTADescripcion);

        jLInfo.setText("Objetivo");

        jBAgregarPlan.setText("Agregar plan");
        jBAgregarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCBCiudad, javax.swing.GroupLayout.Alignment.LEADING, 0, 126, Short.MAX_VALUE)
                                    .addComponent(jTFInfoPlan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFPresupuesto)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRBActividad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBProyecto))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTFCodigo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(jLInfo))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAgregarPlan))
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBActividad)
                            .addComponent(jRBProyecto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCBCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLInfo)
                    .addComponent(jTFInfoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAgregarPlan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Info programa"));

        jBCrearPrograma.setText("Crear programa");
        jBCrearPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearProgramaActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo programa");

        jTFCodigoPrograma.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCrearPrograma)
                .addGap(86, 86, 86))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jTFCodigoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCodigoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jBCrearPrograma)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Crear programas", jPanel2);

        jTInfoPrograma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Cedula responsable", "Presupuesto total"
            }
        ));
        jScrollPane2.setViewportView(jTInfoPrograma);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBEliminarPrograma.setText("Eliminar programa");
        jBEliminarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarProgramaActionPerformed(evt);
            }
        });

        jBMas.setText("Ver informacion");
        jBMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBEliminarPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBMas)
                .addGap(18, 18, 18)
                .addComponent(jBEliminarPrograma)
                .addGap(43, 43, 43))
        );

        jTDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ciudad", "Descripcion", "Presupuesto"
            }
        ));
        jScrollPane3.setViewportView(jTDetalles);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver programas", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBActividadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRBActividadStateChanged
        // TODO add your handling code here:
        if (jRBActividad.isSelected()) {
            jLInfo.setText("Objetivo");
        } else {
            jLInfo.setText("Nombre");
        }
    }//GEN-LAST:event_jRBActividadStateChanged

    private void jRBProyectoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRBProyectoStateChanged
        // TODO add your handling code here:
        if (jRBProyecto.isSelected()) {
            jLInfo.setText("Nombre");
        } else {
            jLInfo.setText("Objetivo");
        }
    }//GEN-LAST:event_jRBProyectoStateChanged

    private void jBAgregarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarPlanActionPerformed
        // TODO add your handling code here:
        try {
            if (!jTFCodigo.getText().isEmpty() && !jTFPresupuesto.getText().isEmpty()
                    && !jTADescripcion.getText().isEmpty() && !jTFInfoPlan.getText().isEmpty()) {
                int cod = Integer.parseInt(jTFCodigo.getText());
                double presupuesto = Double.parseDouble(jTFPresupuesto.getText());
                String ciudad = (String) jCBCiudad.getSelectedItem();
                String descripcion = jTADescripcion.getText();
                String info = jTFInfoPlan.getText();
                if (jRBActividad.isSelected()) {
                    Actividad actividad = new Actividad(info, cod, presupuesto, ciudad, descripcion);
                    planes.add(actividad);
                } else {
                    Proyecto proyecto = new Proyecto(info, cod, presupuesto, ciudad, descripcion);
                    planes.add(proyecto);
                }
                JOptionPane.showMessageDialog(null, "El plan ha sido agregado");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Se han ingresado letras en campos numericos");
        }
    }//GEN-LAST:event_jBAgregarPlanActionPerformed

    private void jBCrearProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearProgramaActionPerformed
        // TODO add your handling code here:
        try {
            if (!jTFCedula.getText().isEmpty() && !jTFNombre.getText().isEmpty()) {
                int cedula = Integer.parseInt(jTFCedula.getText());
                String nombre = jTFNombre.getText();
                int codigo = Integer.parseInt(jTFCodigoPrograma.getText());
                Responsable responsable = new Responsable(cedula, nombre);
                Programa programa = new Programa(responsable, codigo);
                programa.setPlanes(planes);
                core.crearDocumento(programa);
                autoIncremental();
                planes = new ArrayList<>();
                refrescarTabla();
                JOptionPane.showMessageDialog(null, "El programa ha sido creado");
                jTFCedula.setText("");
                jTFNombre.setText("");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar la cedula y el nombre del responsable");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Se han ingresado letras en campos numericos");
        }
    }//GEN-LAST:event_jBCrearProgramaActionPerformed

    private void jBEliminarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarProgramaActionPerformed
        // TODO add your handling code here:
        try {
            int fila = jTInfoPrograma.getSelectedRow();
            if (fila >= 0) {
                int valor = JOptionPane.showConfirmDialog(null, "¿Desea eliminar lel programa?", "Eliminar programa", JOptionPane.YES_NO_OPTION);
                if (valor == 0) {
                    int idPrograma = (int) jTInfoPrograma.getValueAt(fila, 0);
                    for (int i = 0; i < core.getDocumentos().size(); i++) {
                        if (core.getDocumentos().get(i) instanceof Programa && core.getDocumentos().get(i).getCodigo() == idPrograma) {
                            core.eliminarDocumento(core.getDocumentos().get(i));
                        }
                    }
                    refrescarTabla();
                    autoIncremental();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione un programa");
            }
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(null, "Error al intentar eliminar");
        }
    }//GEN-LAST:event_jBEliminarProgramaActionPerformed

    private void jBMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMasActionPerformed
        // TODO add your handling code here:
        try {
            int fila = jTInfoPrograma.getSelectedRow();
            int idCompra = (int) jTInfoPrograma.getValueAt(fila, 0);
            Programa prog = (Programa) core.buscarDocumento(idCompra);
            DefaultTableModel dtm = (DefaultTableModel) jTDetalles.getModel();
            dtm.setRowCount(0);
            for (int i = 0; i < prog.getPlanes().size(); i++) {
                dtm.addRow(new Object[]{prog.getPlanes().get(i).getCiudad(),
                    prog.getPlanes().get(i).getDescripcion(), prog.getPlanes().get(i).getPresupuesto()});
            }
        } catch (ClassCastException | ArrayIndexOutOfBoundsException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Error al intentar ver detalles");
        }
    }//GEN-LAST:event_jBMasActionPerformed

    /**
     * autoincremental para compra
     */
    public void autoIncremental() {
        if (core.getDocumentos().isEmpty()) {
            jTFCodigoPrograma.setText(0 + "");
        } else {
            int auto = core.getDocumentos().get(core.getDocumentos().size() - 1).getCodigo() + 1;
            jTFCodigoPrograma.setText(auto + "");
        }
    }

    /**
     * refresca la tabla de compras
     */
    public void refrescarTabla() {
        DefaultTableModel dtm = (DefaultTableModel) jTInfoPrograma.getModel();
        dtm.setRowCount(0);
        for (int i = 0; i < core.getDocumentos().size(); i++) {
            if (core.getDocumentos().get(i) instanceof Programa) {
                Programa prog = (Programa) core.getDocumentos().get(i);
                double total = 0;
                for (int j = 0; j < prog.getPlanes().size(); j++) {
                    total = total + prog.getPlanes().get(j).getPresupuesto();
                }
                dtm.addRow(new Object[]{prog.getCodigo(), prog.getResponsable().getCedula(), total});
            }
        }
    }

    /**
     * limpia campos de la ventana
     */
    public void limpiarCampos() {
        jTFCodigo.setText("");
        jTFPresupuesto.setText("");
        jCBCiudad.setSelectedIndex(0);
        jTFInfoPlan.setText("");
        jTADescripcion.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAgregarPlan;
    private javax.swing.JButton jBCrearPrograma;
    private javax.swing.JButton jBEliminarPrograma;
    private javax.swing.JButton jBMas;
    private javax.swing.JComboBox<String> jCBCiudad;
    private javax.swing.JLabel jLInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRBActividad;
    private javax.swing.JRadioButton jRBProyecto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTable jTDetalles;
    private javax.swing.JTextField jTFCedula;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFCodigoPrograma;
    private javax.swing.JTextField jTFInfoPlan;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFPresupuesto;
    private javax.swing.JTable jTInfoPrograma;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
