/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guicompras;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modulocompras.Bien;
import modulocompras.Detalle;
import modulocompras.Inversion;
import modulocompras.Servicio;
import modulocore.Compra;
import modulocore.Core;

/**
 *
 * @author JAIRO
 */
public class VentanaCompra extends javax.swing.JFrame {

    /**
     * coreeeeee
     */
    private Core core;

    /**
     * bienes agregados a una compra
     */
    private List<Bien> bienesAgregados;

    /**
     * catidad del bien agregado
     */
    private List<Integer> cantidadBien;

    /**
     * Creates new form VentaCompra
     */
    public VentanaCompra() {
        initComponents();
        core = new Core();
        bienesAgregados = new ArrayList<>();
        cantidadBien = new ArrayList<>();
        jRBInversion.setSelected(true);
        jTFTotal.setText(0 + "");
        autoIncremental();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFCodigoCompra = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFCodigoBien = new javax.swing.JTextField();
        jTFNombreBien = new javax.swing.JTextField();
        jRBInversion = new javax.swing.JRadioButton();
        jRBServicio = new javax.swing.JRadioButton();
        jLDetalle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAInfo = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        jBAgregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTFVelor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFTotal = new javax.swing.JTextField();
        jBComprar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTInfoVentas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jBMas = new javax.swing.JButton();
        jBEliminarCompra = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTDetalles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setEnabled(false);

        jLabel1.setText("Codigo");

        jTFCodigoCompra.setEditable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar bien"));

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Tipo bien");

        buttonGroup1.add(jRBInversion);
        jRBInversion.setText("inversion");
        jRBInversion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRBInversionStateChanged(evt);
            }
        });

        buttonGroup1.add(jRBServicio);
        jRBServicio.setText("servicio");
        jRBServicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRBServicioStateChanged(evt);
            }
        });

        jLDetalle.setText("detalle");

        jTAInfo.setColumns(20);
        jTAInfo.setRows(5);
        jScrollPane2.setViewportView(jTAInfo);

        jLabel6.setText("Cantidad");

        jBAgregar.setText("Agregar a compra");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jLabel7.setText("Valor");

        jLabel5.setText("Total");

        jTFTotal.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jTFCodigoBien, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jTFNombreBien, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jRBInversion)
                        .addGap(18, 18, 18)
                        .addComponent(jRBServicio))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLDetalle)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFCantidad)
                            .addComponent(jTFVelor, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                    .addComponent(jBAgregar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTFTotal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFCodigoBien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTFNombreBien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTFVelor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRBInversion)
                    .addComponent(jRBServicio)
                    .addComponent(jBAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDetalle)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jBComprar.setText("Comprar");
        jBComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTFCodigoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBComprar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFCodigoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBComprar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear Compra", jPanel1);

        jTInfoVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Fecha", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTInfoVentas);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBMas.setText("Ver informacion");
        jBMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMasActionPerformed(evt);
            }
        });

        jBEliminarCompra.setText("Eliminar compra");
        jBEliminarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBEliminarCompra))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jBMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(188, 188, 188))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBMas)
                .addGap(18, 18, 18)
                .addComponent(jBEliminarCompra)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Valor unitario"
            }
        ));
        jScrollPane3.setViewportView(jTDetalles);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver compras", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        try {
            if (!jTFCodigoBien.getText().isEmpty() && !jTFCantidad.getText().isEmpty()
                    && !jTFNombreBien.getText().isEmpty() && !jTFVelor.getText().isEmpty()
                    && !jTAInfo.getText().isEmpty()) {
                Bien bien;
                int codigo = Integer.parseInt(jTFCodigoBien.getText());
                String nombre = jTFNombreBien.getText();
                double valor = Double.parseDouble(jTFVelor.getText());
                int cant = Integer.parseInt(jTFCantidad.getText());
                if (jRBInversion.isSelected()) {
                    Inversion in = new Inversion(jTAInfo.getText(), 123);
                    bien = new Bien(codigo, nombre, in, valor);

                } else {
                    Servicio serv = new Servicio(jTAInfo.getText(), 76152);
                    bien = new Bien(codigo, nombre, serv, valor);
                }
                cantidadBien.add(cant);
                bienesAgregados.add(bien);
                double total = Double.parseDouble(jTFTotal.getText()) + (cant * valor);
                jTFTotal.setText(total + "");
                JOptionPane.showMessageDialog(null, "El bien ha sido agregado a la compra");
            } else {
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Se han ingresado letras en campos numericos");
        }
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jRBServicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRBServicioStateChanged
        // TODO add your handling code here:
        if (jRBServicio.isSelected()) {
            jLDetalle.setText("Compañia");
        } else {
            jLDetalle.setText("Detalle");
        }
    }//GEN-LAST:event_jRBServicioStateChanged

    private void jBComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBComprarActionPerformed
        // TODO add your handling code here:
        try {
            Compra compra = new Compra(Calendar.getInstance().getTime(),
                    Double.parseDouble(jTFTotal.getText()), Integer.parseInt(jTFCodigoCompra.getText()));
            for (int i = 0; i < bienesAgregados.size(); i++) {
                Detalle detalle = new Detalle(compra, bienesAgregados.get(i), cantidadBien.get(i));
                compra.getDetalles().add(detalle);
            }
            bienesAgregados = new ArrayList<>();
            cantidadBien = new ArrayList<>();
            core.crearDocumento(compra);
            jTFCodigoCompra.setText(String.valueOf(core.getDocumentos().size()));
            limpiarCamposCrear();
            refrescarTabla();
            autoIncremental();
            JOptionPane.showMessageDialog(null, "La compra ha sido creada");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Se han ingresado letras en campos numericos");
        }
    }//GEN-LAST:event_jBComprarActionPerformed

    private void jRBInversionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRBInversionStateChanged
        // TODO add your handling code here:
        if (jRBInversion.isSelected()) {
            jLDetalle.setText("Detalle");
        } else {
            jLDetalle.setText("Compañia");
        }
    }//GEN-LAST:event_jRBInversionStateChanged

    private void jBEliminarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarCompraActionPerformed
        // TODO add your handling code here:
        try {
            int fila = jTInfoVentas.getSelectedRow();
            if (fila >= 0) {
                int valor = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la compra?", "Eliminar compra", JOptionPane.YES_NO_OPTION);
                if (valor == 0) {
                    int idCompra = (int) jTInfoVentas.getValueAt(fila, 0);
                    for (int i = 0; i < core.getDocumentos().size(); i++) {
                        if (core.getDocumentos().get(i) instanceof Compra && core.getDocumentos().get(i).getCodigo() == idCompra) {
                            core.eliminarDocumento(core.getDocumentos().get(i));
                        }
                    }
                    refrescarTabla();
                    autoIncremental();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione una compra");
            }
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(null, "Error al intentar eliminar");
        }
    }//GEN-LAST:event_jBEliminarCompraActionPerformed

    private void jBMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMasActionPerformed
        // TODO add your handling code here:
        try {
            int fila = jTInfoVentas.getSelectedRow();
            int idCompra = (int) jTInfoVentas.getValueAt(fila, 0);
            Compra com = (Compra) core.buscarDocumento(idCompra);
            DefaultTableModel dtm = (DefaultTableModel) jTDetalles.getModel();
            dtm.setRowCount(0);
            for (int i = 0; i < com.getDetalles().size(); i++) {
                dtm.addRow(new Object[]{com.getDetalles().get(i).getBien().getNombre(),
                    com.getDetalles().get(i).getCantidadBien(), com.getDetalles().get(i).getBien().getValor()});
            }
        } catch (ClassCastException | ArrayIndexOutOfBoundsException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Error al intentar ver detalles");
        }
    }//GEN-LAST:event_jBMasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCompra().setVisible(true);
            }
        });
    }

    /**
     * refresca la tabla de compras
     */
    public void refrescarTabla() {
        DefaultTableModel dtm = (DefaultTableModel) jTInfoVentas.getModel();
        dtm.setRowCount(0);
        for (int i = 0; i < core.getDocumentos().size(); i++) {
            if (core.getDocumentos().get(i) instanceof Compra) {
                Compra com = (Compra) core.getDocumentos().get(i);
                dtm.addRow(new Object[]{com.getCodigo(), com.getFechaCompra(), com.getTotalCompra()});
            }
        }
    }

    /**
     * autoincremental para compra
     */
    public void autoIncremental() {
        if (core.getDocumentos().isEmpty()) {
            jTFCodigoCompra.setText(0 + "");
        } else {
            int auto = core.getDocumentos().get(core.getDocumentos().size() - 1).getCodigo() + 1;
            jTFCodigoCompra.setText(auto + "");
        }
    }

    /**
     * limpia campos al realizar una compra
     */
    public void limpiarCamposCrear() {
        jTFCodigoBien.setText("");
        jTFCantidad.setText("");
        jTFNombreBien.setText("");
        jTFTotal.setText(0 + "");
        jTFVelor.setText("");
        jTAInfo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBComprar;
    private javax.swing.JButton jBEliminarCompra;
    private javax.swing.JButton jBMas;
    private javax.swing.JLabel jLDetalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBInversion;
    private javax.swing.JRadioButton jRBServicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTAInfo;
    private javax.swing.JTable jTDetalles;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFCodigoBien;
    private javax.swing.JTextField jTFCodigoCompra;
    private javax.swing.JTextField jTFNombreBien;
    private javax.swing.JTextField jTFTotal;
    private javax.swing.JTextField jTFVelor;
    private javax.swing.JTable jTInfoVentas;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
